
MoreJSEvents.villagerTrades((event) => {

    // Trades for cleric

    
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 15, 20)], "kubejs:transmutation_stone")
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 6, 12)], "kubejs:universal_upgrade_core")
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 6, 12)], "minecraft:ender_pearl")
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 1, 5)], "mekanism:cardboard_box")
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 1, 5)], "ae2:certus_quartz_crystal")
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 1, 5)], "camera:camera")
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 1, 5)], "torchmaster:megatorch")
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 6, 8)], "ars_nouveau:novice_spell_book")
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 6, 8)], 'artifacts:obsidian_skull')
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 6, 8)], 'artifacts:cloud_in_a_bottle')
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 6, 8)], 'artifacts:charm_of_sinking')
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 6, 8)], 'artifacts:thorn_pendant')
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 6, 8)], 'artifacts:flame_pendant')
    event.addTrade("cleric", 1, [TradeItem.of("kubejs:one_dollar", 6, 8)], 'securitycraft:bucket_f_water')
    
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:five_dollar", 1, 2)], "artifacts:panic_necklace")
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:five_dollar", 1, 2)], "artifacts:shock_pendant")
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:five_dollar", 1, 2)], "artifacts:flame_pendant")
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:five_dollar", 1, 2)], "artifacts:thorn_pendant")
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:five_dollar", 1, 2)], "artifacts:charm_of_sinking")
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], "occultism:otherstone")
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 8)], "occultism:spirit_torch")
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], "occultism:dictionary_of_spirits")
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], 'ars_nouveau:amulet_of_mana_boost')
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], 'darkutils:charm_warding')
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], 'darkutils:charm_sleep')
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], 'darkutils:charm_portal')
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], 'artifacts:helium_flamingo')
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], 'artifacts:crystal_heart')
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], 'artifacts:universal_attractor')
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], 'artifacts:antidote_vessel')
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], Item.of('occultism:dictionary_of_spirits', '{"modonomicon:book_id":"occultism:dictionary_of_spirits"}'))
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], Item.of('occultism:otherworld_goggles', '{Damage:0}'))
    event.addTrade("cleric", 2, [TradeItem.of("kubejs:one_dollar", 2, 5)], Item.of('waystones:warp_stone', '{Damage:0}'))

    event.addTrade("cleric", 3, [TradeItem.of("kubejs:five_dollar", 6, 8)], "ars_nouveau:apprentice_spell_book")
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:five_dollar", 6, 8)], "mahoutsukai:mortar")
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:five_dollar", 6, 8)], "mahoutsukai:mystic_staff")
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:five_dollar", 6, 8)], "mahoutsukai:replica")
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], "mahoutsukai:weapon_projectile_bow")
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'ars_nouveau:dull_trinket')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'ars_nouveau:source_gem')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'artifacts:shock_pendant')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'artifacts:cross_necklace')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'ars_nouveau:amulet_of_mana_regen')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'ars_nouveau:amulet_of_mana_boost')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'darkutils:charm_warding')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'darkutils:charm_sleep')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'artifacts:flippers')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'artifacts:bunny_hoppers')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'artifacts:pocket_piston')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'artifacts:fire_gauntlet')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'artifacts:power_glove')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'artifacts:feral_claws')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'thermal:flux_capacitor')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'thermal:potion_infuser')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'thermal:potion_quiver')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'ars_nouveau:source_gem')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'artifacts:shock_pendant')
    event.addTrade("cleric", 3, [TradeItem.of("kubejs:ten_dollar", 8, 12)], 'artifacts:cross_necklace')  

    event.addTrade("cleric", 4, [TradeItem.of("kubejs:ten_dollar", 2, 5)], "ars_nouveau:archmage_spell_book")
    event.addTrade("cleric", 4, [TradeItem.of("kubejs:ten_dollar", 1, 2)], "minecraft:experience_bottle")
    event.addTrade("cleric", 4, [TradeItem.of("kubejs:ten_dollar", 1, 2)], "minecraft:enchanting_table")
    event.addTrade("cleric", 4, [TradeItem.of("kubejs:ten_dollar", 8, 12)], "enderio:enchanter")
    event.addTrade("cleric", 4, [TradeItem.of("kubejs:ten_dollar", 2, 5)], "industrialforegoing:enchantment_sorter")
    event.addTrade("cleric", 4, [TradeItem.of("kubejs:ten_dollar", 2, 5)], "industrialforegoing:enchantment_applicator")
    event.addTrade("cleric", 4, [TradeItem.of("kubejs:ten_dollar", 2, 5)], "industrialforegoing:enchantment_extractor")
    event.addTrade("cleric", 4, [TradeItem.of("kubejs:ten_dollar", 2, 5)], "industrialforegoing:enchantment_factory")
    event.addTrade("cleric", 4, [TradeItem.of("kubejs:ten_dollar", 3, 7)], "rats:rat_upgrade_enchanter")

    // Enchantment Trades

    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('enderio:withering', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:depth_strider', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:thorns', 4))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:aqua_affinity', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:respiration', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:projectile_protection', 4))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:blast_protection', 4))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:feather_falling', 4))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:fire_protection', 4))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:protection', 4))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:fortune', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:looting', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:unbreaking', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:silk_touch', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:efficiency', 5))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:swift_sneak', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:soul_speed', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:binding_curse', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:frost_walker', 2))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:vanishing_curse', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:mending', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:quick_charge', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:multishot', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:impaling', 5))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:loyalty', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:lure', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:luck_of_the_sea', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('minecraft:infinity', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:vitality', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:reach', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:xp_boost', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:air_affinity', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:magic_protection', 4))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('deeperdarker:catalysis', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('cofh_core:holding', 4))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ars_nouveau:mana_boost', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ars_nouveau:mana_regen', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:bulwark', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:angler', 2))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:volley', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:trueshot', 2))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:quick_draw', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:hunter', 2))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:excavating', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:vorpal', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:frost_aspect', 2))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('enderio:xp_boost', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('enderio:repellent', 4))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('additionaladditions:precision', 3))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:curse_mercy', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:curse_fool', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:soulbound', 1))
    event.addTrade("cleric", 5, [TradeItem.of("kubejs:fifty_dollar", 5, 12)], Item.of('minecraft:enchanted_book').enchant('ensorcellation:phalanx', 2))
   
    
    // Avaritia Trades

    event.addTrade("cleric", 5, [TradeItem.of("kubejs:one_thousand_dollar", 8, 30)], "avaritia:endest_pearl")
   

})